---
- name: add ssh key
  vars:
    ansible_python_interpreter: /usr/bin/python3  
  hosts: all 
  become: yes
  tasks:
  - name: add comment to .bashrc
    ansible.builtin.lineinfile:
        path: "/root/.bashrc"        
        line: '[[ $- != *i* ]] && return'
    check_mode: yes

  - name: Ensure SELinux is set to enforcing mode
    ansible.builtin.lineinfile:
      path: /etc/selinux/config
      regexp: '^SELINUX='
      line: SELINUX=disabled

  - name: add PS1
    ansible.builtin.lineinfile:
      create: yes
      mode: 0600
      dest: /root/.bashrc
      owner: root
      regexp: '^PS1='
      line: 'PS1="\[$(tput setaf 6)\]\@ \[\033[35;1m\]\u\[\033[0m\]@\[\033[31;1m\]\h \[\033[32;1m\]$PWD\[\033[0m\] [\[\033[35m\]\#\[\033[0m\]]\[\033[31m\]\$\[\033[0m\] "'
      state: present


  - name: add PS1
    ansible.builtin.lineinfile:
      create: yes
      mode: 0600
      dest: /root/.bashrc
      owner: root

      regexp: '{{item.From}}'
      # Line to Replace with
      line: '{{item.To}}'
      state: present  
      path: /root/.bashrc
    with_items:
      - { From: 'alias vi=', To: 'alias vim="vi"'}