---
- name: add ssh key
  vars:
    ansible_python_interpreter: /usr/bin/python3  
  hosts: all 
  become: yes
  tasks:
  - name: add comment to .bashrc
    ansible.builtin.lineinfile:
        path: "/root/.bashrc"        
        line: '[[ $- != *i* ]] && return'
    check_mode: yes

  - name: Ensure SELinux is set to enforcing mode
    ansible.builtin.lineinfile:
      path: /etc/selinux/config
      regexp: '^SELINUX='
      line: SELINUX=disabled