---
- name: add ssh key
  vars:
    ansible_python_interpreter: /usr/bin/python3  
  hosts: all 
  become: yes
  tasks:
  - name: add comment to .bashrc in root profile
    ansible.builtin.lineinfile:
        path: "/root/.bashrc"        
        line: '[[ $- != *i* ]] && return'
    check_mode: yes
  - name: add comment to .bashrc in ecloaiza profile
    ansible.builtin.lineinfile:
        path: "/home/ecloaiza/.bashrc"        
        line: '[[ $- != *i* ]] && return'
    check_mode: yes


  - name: Ensure SELinux is set to enforcing mode
    ansible.builtin.lineinfile:
      path: /etc/selinux/config
      regexp: '^SELINUX='
      line: SELINUX=disabled

  - name: add PS1
    ansible.builtin.lineinfile:
      create: yes
      mode: 0600
      dest: /root/.bashrc
      owner: root
      regexp: '^PS1='
      line: 'PS1="\[$(tput setaf 6)\]\@ \[\033[35;1m\]\u\[\033[0m\]@\[\033[31;1m\]\h \[\033[32;1m\]$PWD\[\033[0m\] [\[\033[35m\]\#\[\033[0m\]]\[\033[31m\]\$\[\033[0m\] "'
      state: present


  - name: add ALIAS for root
    ansible.builtin.lineinfile:
      create: yes
      mode: 0600
      dest: /root/.bashrc
      owner: root

      regexp: '{{item.From}}'
      # Line to Replace with
      line: '{{item.To}}'
      state: present  
      path: /root/.bashrc
    with_items:
      - { From: 'alias vi=', To: 'alias vim="vi"'}
      - { From: 'alias rm=', To: 'alias rm="rm -i"'}
      - { From: 'alias U=', To: 'alias U="cd .."'}
      - { From: 'alias ls=', To: 'alias ls="ls -lA --color=yes | less -r -E -X"'}
      - { From: 'alias cp=', To: 'alias cp="cp -ip"'}
      - { From: 'alias mv=', To: 'alias mv="mv -i"'}
      - { From: 'alias ll=', To: 'alias ll="ls -A | less -r -E -X"'}
      - { From: 'alias p=', To: 'alias pp="ping -c 3 google.com"'}
      - { From: 'alias l=', To: 'alias l="ll"'}
      - { From: 'alias space=', To: 'alias space="du -h --max-depth=1"'}

  - name: add ALIAS for ecloaiza
    ansible.builtin.lineinfile:
      create: yes
      mode: 0600
      dest: /home/ecloaiza/.bashrc
      owner: ecloaiza

      regexp: '{{item.From}}'
      # Line to Replace with
      line: '{{item.To}}'
      state: present  
      path: /home/ecloaiza/.bashrc
    with_items:
      - { From: 'alias vi=', To: 'alias vim="vi"'}
      - { From: 'alias rm=', To: 'alias rm="rm -i"'}
      - { From: 'alias U=', To: 'alias U="cd .."'}
      - { From: 'alias ls=', To: 'alias ls="ls -lA --color=yes | less -r -E -X"'}
      - { From: 'alias cp=', To: 'alias cp="cp -ip"'}
      - { From: 'alias mv=', To: 'alias mv="mv -i"'}
      - { From: 'alias ll=', To: 'alias ll="ls -A | less -r -E -X"'}
      - { From: 'alias p=', To: 'alias pp="ping -c 3 google.com"'}
      - { From: 'alias l=', To: 'alias l="ll"'}
      - { From: 'alias space=', To: 'alias space="sudo du -h --max-depth=1"'}



  - name: add BANNER lines - for root
    ansible.builtin.lineinfile:
        create: yes
        mode: 0600
        dest: /root/.bashrc
        owner: root
        line: '{{ item }}'
    with_items:
      - 'echo -e -n "\E[1;34m"'
      - 'figlet -w 50 "$(hostname)"'
      - 'echo "├──Emmanuel Loaiza"'
      - 'echo "├──ELIKESBIKES"'
      - 'echo "└──"$(date +"%B%e"), $(date +"%Y")'
      - 'echo -e -n "\E[1;34m"'
      - 'uptime'
      - 'echo -e "\E[0m"'

  - name: add BANNER lines - for ecloaiza
    ansible.builtin.lineinfile:
        create: yes
        mode: 0600
        dest: /home/ecloaiza/.bashrc
        owner: ecloaiza
        line: '{{ item }}'
    with_items:
      - 'echo -e -n "\E[1;34m"'
      - 'figlet -w 50 "$(hostname)"'
      - 'echo "├──Emmanuel Loaiza"'
      - 'echo "├──ELIKESBIKES"'
      - 'echo "└──"$(date +"%B%e"), $(date +"%Y")'
      - 'echo -e -n "\E[1;34m"'
      - 'uptime'
      - 'echo -e "\E[0m"'