---
- name: Install QEMU Guest Agent
  hosts: your_centos_servers
  become: true

  tasks:
    - name: Install qemu-guest-agent package
      yum:
        name: qemu-guest-agent
        state: present

    - name: Start and enable qemu-guest-agent service
      service:
        name: qemu-guest-agent
        state: started
        enabled: yes
